---

name: HERMESv3_BU_v1.1.1

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python ~= 3.8
  - openmpi = 4.0.5
  - mpi4py = 3.1.4
  - geopandas <= 0.5.1
  - pandas ~= 0.25.3
  - numpy <= 1.19.5
  - timezonefinder ~= 4.0.0
  - configargparse
  - netcdf4
  - rasterio
